### ISSUE TITLE
Select component breaks if wrapped by <form> tag

### ISSUE THREAD

**Issue by MarcelloPaiva** [alexandrtovmach/react-figma-plugin-ds#13]
I created a Figma plugin with a React app UI, and I had a \<form\> tag wrapping my Input components along with a Select component and some Checkboxes. All of the components worked as expected except for the Select component, which would crash my plugin UI every time I clicked on it. I changed the \<form\> tag to a \<div\> and then it worked fine.

I doubt this is the intended behavior, but if it is could someone explain why?

**Comment by alexandrtovmach** [comment]
not sure why it's crashing, but select component implemented not in really semantic way, and used `div`/`button`/`li` instead of `select`/`option` elements. Never heard about that's can crash the form, but maybe you have some listener on it, which expect wrong things?

**Comment by lukasoppermann** [comment]
Hey @alexandrtovmach the issue may be the button (used to create the select) not having a `type="button"`. 

Because of this the button defaults to `type="submit"` which means clicking on the select to open it results in the form being instantly submitted. 

This makes definitely makes it unusable for me.
